[2023-11-23T23:01:30.018+0000] {processor.py:157} INFO - Started process (PID=42) to work on /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:01:30.035+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_extract_despesas.py for tasks to queue
[2023-11-23T23:01:30.068+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:01:30.068+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:01:30.270+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:01:30.239+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/dag_extract_despesas.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_despesas.py", line 4, in <module>
    from scripts.get_despesas_stg import extractDespesas
ModuleNotFoundError: No module named 'scripts'
[2023-11-23T23:01:30.277+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:01:30.587+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_extract_despesas.py took 0.633 seconds
[2023-11-23T23:02:01.070+0000] {processor.py:157} INFO - Started process (PID=96) to work on /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:02:01.083+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_extract_despesas.py for tasks to queue
[2023-11-23T23:02:01.107+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:02:01.106+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:02:01.210+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:02:01.172+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/dag_extract_despesas.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_despesas.py", line 4, in <module>
    from scripts.get_despesas_stg import extractDespesas
ModuleNotFoundError: No module named 'scripts'
[2023-11-23T23:02:01.221+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:02:02.059+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_extract_despesas.py took 1.037 seconds
[2023-11-23T23:02:32.400+0000] {processor.py:157} INFO - Started process (PID=152) to work on /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:02:32.403+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_extract_despesas.py for tasks to queue
[2023-11-23T23:02:32.407+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:02:32.407+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:02:32.445+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:02:32.437+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/dag_extract_despesas.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_despesas.py", line 4, in <module>
    from scripts.get_despesas_stg import extractDespesas
ModuleNotFoundError: No module named 'scripts'
[2023-11-23T23:02:32.447+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:02:32.467+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_extract_despesas.py took 0.071 seconds
[2023-11-23T23:03:03.027+0000] {processor.py:157} INFO - Started process (PID=207) to work on /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:03:03.028+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_extract_despesas.py for tasks to queue
[2023-11-23T23:03:03.031+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:03:03.030+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:03:03.062+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:03:03.056+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/dag_extract_despesas.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_despesas.py", line 4, in <module>
    from scripts.get_despesas_stg import extractDespesas
ModuleNotFoundError: No module named 'scripts'
[2023-11-23T23:03:03.064+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:03:03.085+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_extract_despesas.py took 0.061 seconds
[2023-11-23T23:03:33.618+0000] {processor.py:157} INFO - Started process (PID=262) to work on /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:03:33.619+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_extract_despesas.py for tasks to queue
[2023-11-23T23:03:33.622+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:03:33.622+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:03:33.656+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:03:33.650+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/dag_extract_despesas.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_despesas.py", line 4, in <module>
    from scripts.get_despesas_stg import extractDespesas
ModuleNotFoundError: No module named 'scripts'
[2023-11-23T23:03:33.659+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:03:33.683+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_extract_despesas.py took 0.069 seconds
[2023-11-23T23:04:03.965+0000] {processor.py:157} INFO - Started process (PID=317) to work on /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:04:03.967+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_extract_despesas.py for tasks to queue
[2023-11-23T23:04:03.969+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:04:03.969+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:04:04.007+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:04:04.000+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/dag_extract_despesas.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_despesas.py", line 4, in <module>
    from scripts.get_despesas_stg import extractDespesas
ModuleNotFoundError: No module named 'scripts'
[2023-11-23T23:04:04.010+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:04:04.033+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_extract_despesas.py took 0.073 seconds
[2023-11-23T23:04:34.308+0000] {processor.py:157} INFO - Started process (PID=372) to work on /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:04:34.310+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_extract_despesas.py for tasks to queue
[2023-11-23T23:04:34.316+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:04:34.315+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:04:34.358+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:04:34.352+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/dag_extract_despesas.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_despesas.py", line 4, in <module>
    from scripts.get_despesas_stg import extractDespesas
ModuleNotFoundError: No module named 'scripts'
[2023-11-23T23:04:34.360+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:04:34.380+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_extract_despesas.py took 0.080 seconds
[2023-11-23T23:05:04.711+0000] {processor.py:157} INFO - Started process (PID=427) to work on /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:05:04.714+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_extract_despesas.py for tasks to queue
[2023-11-23T23:05:04.720+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:05:04.718+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:05:04.763+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:05:04.756+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/dag_extract_despesas.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_despesas.py", line 4, in <module>
    from scripts.get_despesas_stg import extractDespesas
ModuleNotFoundError: No module named 'scripts'
[2023-11-23T23:05:04.765+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:05:04.790+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_extract_despesas.py took 0.086 seconds
[2023-11-23T23:05:34.992+0000] {processor.py:157} INFO - Started process (PID=482) to work on /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:05:34.994+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_extract_despesas.py for tasks to queue
[2023-11-23T23:05:35.000+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:05:34.997+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:05:35.037+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:05:35.029+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/dag_extract_despesas.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_despesas.py", line 4, in <module>
    from scripts.get_despesas_stg import extractDespesas
ModuleNotFoundError: No module named 'scripts'
[2023-11-23T23:05:35.039+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:05:35.058+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_extract_despesas.py took 0.069 seconds
[2023-11-23T23:06:05.620+0000] {processor.py:157} INFO - Started process (PID=537) to work on /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:06:05.622+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_extract_despesas.py for tasks to queue
[2023-11-23T23:06:05.625+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:06:05.625+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:06:05.658+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:06:05.652+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/dag_extract_despesas.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_despesas.py", line 4, in <module>
    from scripts.get_despesas_stg import extractDespesas
ModuleNotFoundError: No module named 'scripts'
[2023-11-23T23:06:05.660+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:06:05.708+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_extract_despesas.py took 0.091 seconds
[2023-11-23T23:06:35.839+0000] {processor.py:157} INFO - Started process (PID=592) to work on /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:06:35.840+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_extract_despesas.py for tasks to queue
[2023-11-23T23:06:35.843+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:06:35.842+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:06:35.872+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:06:35.866+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/dag_extract_despesas.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_despesas.py", line 4, in <module>
    from scripts.get_despesas_stg import extractDespesas
ModuleNotFoundError: No module named 'scripts'
[2023-11-23T23:06:35.874+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:06:35.894+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_extract_despesas.py took 0.058 seconds
[2023-11-23T23:07:06.041+0000] {processor.py:157} INFO - Started process (PID=647) to work on /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:07:06.043+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_extract_despesas.py for tasks to queue
[2023-11-23T23:07:06.046+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:07:06.046+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:07:06.080+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:07:06.074+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/dag_extract_despesas.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_despesas.py", line 4, in <module>
    from scripts.get_despesas_stg import extractDespesas
ModuleNotFoundError: No module named 'scripts'
[2023-11-23T23:07:06.083+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:07:06.128+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_extract_despesas.py took 0.090 seconds
[2023-11-23T23:07:36.706+0000] {processor.py:157} INFO - Started process (PID=702) to work on /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:07:36.707+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_extract_despesas.py for tasks to queue
[2023-11-23T23:07:36.711+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:07:36.710+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:07:36.748+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:07:36.742+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/dag_extract_despesas.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_despesas.py", line 4, in <module>
    from scripts.get_despesas_stg import extractDespesas
ModuleNotFoundError: No module named 'scripts'
[2023-11-23T23:07:36.751+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:07:36.796+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_extract_despesas.py took 0.094 seconds
[2023-11-23T23:08:06.949+0000] {processor.py:157} INFO - Started process (PID=757) to work on /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:08:06.951+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_extract_despesas.py for tasks to queue
[2023-11-23T23:08:06.954+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:08:06.953+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:08:06.993+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:08:06.986+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/dag_extract_despesas.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_despesas.py", line 4, in <module>
    from scripts.get_despesas_stg import extractDespesas
ModuleNotFoundError: No module named 'scripts'
[2023-11-23T23:08:06.996+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:08:07.043+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_extract_despesas.py took 0.098 seconds
[2023-11-23T23:08:37.251+0000] {processor.py:157} INFO - Started process (PID=812) to work on /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:08:37.252+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_extract_despesas.py for tasks to queue
[2023-11-23T23:08:37.255+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:08:37.255+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:08:37.297+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:08:37.288+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/dag_extract_despesas.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_despesas.py", line 4, in <module>
    from scripts.get_despesas_stg import extractDespesas
ModuleNotFoundError: No module named 'scripts'
[2023-11-23T23:08:37.300+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:08:37.330+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_extract_despesas.py took 0.083 seconds
[2023-11-23T23:09:07.810+0000] {processor.py:157} INFO - Started process (PID=867) to work on /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:09:07.812+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_extract_despesas.py for tasks to queue
[2023-11-23T23:09:07.814+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:09:07.814+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:09:07.852+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:09:07.845+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/dag_extract_despesas.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_despesas.py", line 4, in <module>
    from scripts.get_despesas_stg import extractDespesas
ModuleNotFoundError: No module named 'scripts'
[2023-11-23T23:09:07.854+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:09:07.876+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_extract_despesas.py took 0.070 seconds
[2023-11-23T23:09:38.186+0000] {processor.py:157} INFO - Started process (PID=922) to work on /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:09:38.188+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_extract_despesas.py for tasks to queue
[2023-11-23T23:09:38.193+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:09:38.193+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:09:38.254+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:09:38.248+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/dag_extract_despesas.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_despesas.py", line 4, in <module>
    from scripts.get_despesas_stg import extractDespesas
ModuleNotFoundError: No module named 'scripts'
[2023-11-23T23:09:38.256+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:09:38.310+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_extract_despesas.py took 0.131 seconds
[2023-11-23T23:10:08.507+0000] {processor.py:157} INFO - Started process (PID=977) to work on /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:10:08.509+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_extract_despesas.py for tasks to queue
[2023-11-23T23:10:08.514+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:10:08.513+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:10:08.573+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:10:08.560+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/dag_extract_despesas.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_despesas.py", line 4, in <module>
    from scripts.get_despesas_stg import extractDespesas
ModuleNotFoundError: No module named 'scripts'
[2023-11-23T23:10:08.578+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:10:08.641+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_extract_despesas.py took 0.141 seconds
[2023-11-23T23:10:38.922+0000] {processor.py:157} INFO - Started process (PID=1032) to work on /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:10:38.925+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_extract_despesas.py for tasks to queue
[2023-11-23T23:10:38.930+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:10:38.929+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:10:38.973+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:10:38.966+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/dag_extract_despesas.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_despesas.py", line 4, in <module>
    from scripts.get_despesas_stg import extractDespesas
ModuleNotFoundError: No module named 'scripts'
[2023-11-23T23:10:38.975+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:10:39.018+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_extract_despesas.py took 0.103 seconds
[2023-11-23T23:11:09.356+0000] {processor.py:157} INFO - Started process (PID=1087) to work on /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:11:09.357+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_extract_despesas.py for tasks to queue
[2023-11-23T23:11:09.360+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:11:09.359+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:11:09.390+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:11:09.384+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/dag_extract_despesas.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_despesas.py", line 4, in <module>
    from scripts.get_despesas_stg import extractDespesas
ModuleNotFoundError: No module named 'scripts'
[2023-11-23T23:11:09.393+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:11:09.416+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_extract_despesas.py took 0.063 seconds
[2023-11-23T23:11:39.502+0000] {processor.py:157} INFO - Started process (PID=1140) to work on /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:11:39.504+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_extract_despesas.py for tasks to queue
[2023-11-23T23:11:39.509+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:11:39.508+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:11:39.545+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:11:39.539+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/dag_extract_despesas.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_despesas.py", line 4, in <module>
    from scripts.get_despesas_stg import extractDespesas
ModuleNotFoundError: No module named 'scripts'
[2023-11-23T23:11:39.547+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:11:39.567+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_extract_despesas.py took 0.072 seconds
[2023-11-23T23:12:10.347+0000] {processor.py:157} INFO - Started process (PID=1195) to work on /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:12:10.349+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_extract_despesas.py for tasks to queue
[2023-11-23T23:12:10.351+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:12:10.351+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:12:10.388+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:12:10.380+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/dag_extract_despesas.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_despesas.py", line 4, in <module>
    from scripts.get_despesas_stg import extractDespesas
ModuleNotFoundError: No module named 'scripts'
[2023-11-23T23:12:10.390+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:12:10.413+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_extract_despesas.py took 0.069 seconds
[2023-11-23T23:12:41.305+0000] {processor.py:157} INFO - Started process (PID=1250) to work on /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:12:41.306+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_extract_despesas.py for tasks to queue
[2023-11-23T23:12:41.309+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:12:41.309+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:12:41.344+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:12:41.338+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/dag_extract_despesas.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_despesas.py", line 4, in <module>
    from scripts.get_despesas_stg import extractDespesas
ModuleNotFoundError: No module named 'scripts'
[2023-11-23T23:12:41.346+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:12:41.365+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_extract_despesas.py took 0.064 seconds
[2023-11-23T23:13:11.630+0000] {processor.py:157} INFO - Started process (PID=1305) to work on /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:13:11.632+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_extract_despesas.py for tasks to queue
[2023-11-23T23:13:11.635+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:13:11.635+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:13:11.669+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:13:11.663+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/dag_extract_despesas.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_despesas.py", line 4, in <module>
    from scripts.get_despesas_stg import extractDespesas
ModuleNotFoundError: No module named 'scripts'
[2023-11-23T23:13:11.673+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:13:11.696+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_extract_despesas.py took 0.071 seconds
[2023-11-23T23:13:42.210+0000] {processor.py:157} INFO - Started process (PID=1360) to work on /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:13:42.212+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_extract_despesas.py for tasks to queue
[2023-11-23T23:13:42.214+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:13:42.214+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:13:42.249+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:13:42.243+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/dag_extract_despesas.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_despesas.py", line 4, in <module>
    from scripts.get_despesas_stg import extractDespesas
ModuleNotFoundError: No module named 'scripts'
[2023-11-23T23:13:42.251+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:13:42.276+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_extract_despesas.py took 0.070 seconds
[2023-11-23T23:14:12.867+0000] {processor.py:157} INFO - Started process (PID=1415) to work on /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:14:12.868+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_extract_despesas.py for tasks to queue
[2023-11-23T23:14:12.871+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:14:12.871+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:14:12.907+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:14:12.900+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/dag_extract_despesas.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_despesas.py", line 4, in <module>
    from scripts.get_despesas_stg import extractDespesas
ModuleNotFoundError: No module named 'scripts'
[2023-11-23T23:14:12.909+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:14:12.929+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_extract_despesas.py took 0.066 seconds
[2023-11-23T23:14:43.109+0000] {processor.py:157} INFO - Started process (PID=1470) to work on /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:14:43.111+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_extract_despesas.py for tasks to queue
[2023-11-23T23:14:43.114+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:14:43.113+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:14:43.149+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:14:43.143+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/dag_extract_despesas.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_despesas.py", line 4, in <module>
    from scripts.get_despesas_stg import extractDespesas
ModuleNotFoundError: No module named 'scripts'
[2023-11-23T23:14:43.151+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:14:43.193+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_extract_despesas.py took 0.087 seconds
[2023-11-23T23:15:13.466+0000] {processor.py:157} INFO - Started process (PID=1525) to work on /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:15:13.467+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_extract_despesas.py for tasks to queue
[2023-11-23T23:15:13.470+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:15:13.469+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:15:13.512+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:15:13.503+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/dag_extract_despesas.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_despesas.py", line 4, in <module>
    from scripts.get_despesas_stg import extractDespesas
ModuleNotFoundError: No module named 'scripts'
[2023-11-23T23:15:13.514+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:15:13.559+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_extract_despesas.py took 0.101 seconds
[2023-11-23T23:15:44.484+0000] {processor.py:157} INFO - Started process (PID=1580) to work on /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:15:44.485+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_extract_despesas.py for tasks to queue
[2023-11-23T23:15:44.489+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:15:44.489+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:15:44.528+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:15:44.521+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/dag_extract_despesas.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_despesas.py", line 4, in <module>
    from scripts.get_despesas_stg import extractDespesas
ModuleNotFoundError: No module named 'scripts'
[2023-11-23T23:15:44.533+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:15:44.554+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_extract_despesas.py took 0.075 seconds
[2023-11-23T23:16:15.242+0000] {processor.py:157} INFO - Started process (PID=1635) to work on /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:16:15.243+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_extract_despesas.py for tasks to queue
[2023-11-23T23:16:15.246+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:16:15.246+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:16:15.282+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:16:15.275+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/dag_extract_despesas.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_despesas.py", line 4, in <module>
    from scripts.get_despesas_stg import extractDespesas
ModuleNotFoundError: No module named 'scripts'
[2023-11-23T23:16:15.285+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:16:15.327+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_extract_despesas.py took 0.090 seconds
[2023-11-23T23:16:45.815+0000] {processor.py:157} INFO - Started process (PID=1691) to work on /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:16:45.817+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_extract_despesas.py for tasks to queue
[2023-11-23T23:16:45.821+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:16:45.820+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:16:45.857+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:16:45.850+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/dag_extract_despesas.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_despesas.py", line 4, in <module>
    from scripts.get_despesas_stg import extractDespesas
ModuleNotFoundError: No module named 'scripts'
[2023-11-23T23:16:45.880+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:16:45.899+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_extract_despesas.py took 0.087 seconds
[2023-11-23T23:17:16.168+0000] {processor.py:157} INFO - Started process (PID=1746) to work on /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:17:16.172+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_extract_despesas.py for tasks to queue
[2023-11-23T23:17:16.179+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:17:16.179+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:17:16.217+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:17:16.210+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/dag_extract_despesas.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_despesas.py", line 4, in <module>
    from scripts.get_despesas_stg import extractDespesas
ModuleNotFoundError: No module named 'scripts'
[2023-11-23T23:17:16.220+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:17:16.251+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_extract_despesas.py took 0.094 seconds
[2023-11-23T23:17:46.477+0000] {processor.py:157} INFO - Started process (PID=1801) to work on /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:17:46.479+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_extract_despesas.py for tasks to queue
[2023-11-23T23:17:46.482+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:17:46.481+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:17:46.518+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:17:46.511+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/dag_extract_despesas.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_despesas.py", line 4, in <module>
    from scripts.get_despesas_stg import extractDespesas
ModuleNotFoundError: No module named 'scripts'
[2023-11-23T23:17:46.520+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:17:46.564+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_extract_despesas.py took 0.090 seconds
[2023-11-23T23:18:17.029+0000] {processor.py:157} INFO - Started process (PID=1856) to work on /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:18:17.031+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_extract_despesas.py for tasks to queue
[2023-11-23T23:18:17.034+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:18:17.034+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:18:17.070+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:18:17.063+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/dag_extract_despesas.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_despesas.py", line 4, in <module>
    from scripts.get_despesas_stg import extractDespesas
ModuleNotFoundError: No module named 'scripts'
[2023-11-23T23:18:17.072+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:18:17.120+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_extract_despesas.py took 0.095 seconds
[2023-11-23T23:18:47.604+0000] {processor.py:157} INFO - Started process (PID=1911) to work on /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:18:47.606+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_extract_despesas.py for tasks to queue
[2023-11-23T23:18:47.610+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:18:47.610+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:18:47.647+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:18:47.640+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/dag_extract_despesas.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_despesas.py", line 4, in <module>
    from scripts.get_despesas_stg import extractDespesas
ModuleNotFoundError: No module named 'scripts'
[2023-11-23T23:18:47.649+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:18:47.675+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_extract_despesas.py took 0.075 seconds
[2023-11-23T23:19:18.237+0000] {processor.py:157} INFO - Started process (PID=1966) to work on /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:19:18.238+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_extract_despesas.py for tasks to queue
[2023-11-23T23:19:18.242+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:19:18.241+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:19:18.275+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:19:18.269+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/dag_extract_despesas.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_despesas.py", line 4, in <module>
    from scripts.get_despesas_stg import extractDespesas
ModuleNotFoundError: No module named 'scripts'
[2023-11-23T23:19:18.277+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:19:18.305+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_extract_despesas.py took 0.072 seconds
[2023-11-23T23:19:48.581+0000] {processor.py:157} INFO - Started process (PID=2021) to work on /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:19:48.582+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_extract_despesas.py for tasks to queue
[2023-11-23T23:19:48.586+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:19:48.586+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:19:48.621+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:19:48.615+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/dag_extract_despesas.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_despesas.py", line 4, in <module>
    from scripts.get_despesas_stg import extractDespesas
ModuleNotFoundError: No module named 'scripts'
[2023-11-23T23:19:48.624+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:19:48.674+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_extract_despesas.py took 0.097 seconds
[2023-11-23T23:20:19.047+0000] {processor.py:157} INFO - Started process (PID=2076) to work on /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:20:19.049+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_extract_despesas.py for tasks to queue
[2023-11-23T23:20:19.052+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:20:19.052+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:20:19.091+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:20:19.083+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/dag_extract_despesas.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_despesas.py", line 4, in <module>
    from scripts.get_despesas_stg import extractDespesas
ModuleNotFoundError: No module named 'scripts'
[2023-11-23T23:20:19.094+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:20:19.131+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_extract_despesas.py took 0.088 seconds
[2023-11-23T23:20:49.941+0000] {processor.py:157} INFO - Started process (PID=2131) to work on /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:20:49.942+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_extract_despesas.py for tasks to queue
[2023-11-23T23:20:49.945+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:20:49.945+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:20:49.980+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:20:49.974+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/dag_extract_despesas.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_despesas.py", line 4, in <module>
    from scripts.get_despesas_stg import extractDespesas
ModuleNotFoundError: No module named 'scripts'
[2023-11-23T23:20:49.983+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:20:50.033+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_extract_despesas.py took 0.096 seconds
[2023-11-23T23:21:20.151+0000] {processor.py:157} INFO - Started process (PID=2186) to work on /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:21:20.152+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_extract_despesas.py for tasks to queue
[2023-11-23T23:21:20.155+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:21:20.155+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:21:20.193+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:21:20.185+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/dag_extract_despesas.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_despesas.py", line 4, in <module>
    from scripts.get_despesas_stg import extractDespesas
ModuleNotFoundError: No module named 'scripts'
[2023-11-23T23:21:20.196+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:21:20.232+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_extract_despesas.py took 0.085 seconds
[2023-11-23T23:21:50.798+0000] {processor.py:157} INFO - Started process (PID=2241) to work on /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:21:50.799+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_extract_despesas.py for tasks to queue
[2023-11-23T23:21:50.803+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:21:50.802+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:21:50.839+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:21:50.832+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/dag_extract_despesas.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_despesas.py", line 4, in <module>
    from scripts.get_despesas_stg import extractDespesas
ModuleNotFoundError: No module named 'scripts'
[2023-11-23T23:21:50.842+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:21:50.881+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_extract_despesas.py took 0.086 seconds
[2023-11-23T23:22:21.210+0000] {processor.py:157} INFO - Started process (PID=2296) to work on /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:22:21.211+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_extract_despesas.py for tasks to queue
[2023-11-23T23:22:21.214+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:22:21.214+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:22:21.250+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:22:21.243+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/dag_extract_despesas.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_despesas.py", line 4, in <module>
    from scripts.get_despesas_stg import extractDespesas
ModuleNotFoundError: No module named 'scripts'
[2023-11-23T23:22:21.252+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:22:21.298+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_extract_despesas.py took 0.092 seconds
[2023-11-23T23:22:51.840+0000] {processor.py:157} INFO - Started process (PID=2351) to work on /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:22:51.841+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_extract_despesas.py for tasks to queue
[2023-11-23T23:22:51.844+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:22:51.844+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:22:51.876+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:22:51.870+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/dag_extract_despesas.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_despesas.py", line 4, in <module>
    from scripts.get_despesas_stg import extractDespesas
ModuleNotFoundError: No module named 'scripts'
[2023-11-23T23:22:51.879+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:22:51.900+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_extract_despesas.py took 0.064 seconds
[2023-11-23T23:23:22.406+0000] {processor.py:157} INFO - Started process (PID=2406) to work on /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:23:22.408+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_extract_despesas.py for tasks to queue
[2023-11-23T23:23:22.411+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:23:22.410+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:23:22.446+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:23:22.440+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/dag_extract_despesas.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_despesas.py", line 4, in <module>
    from scripts.get_despesas_stg import extractDespesas
ModuleNotFoundError: No module named 'scripts'
[2023-11-23T23:23:22.448+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:23:22.491+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_extract_despesas.py took 0.089 seconds
[2023-11-23T23:23:53.035+0000] {processor.py:157} INFO - Started process (PID=2461) to work on /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:23:53.036+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_extract_despesas.py for tasks to queue
[2023-11-23T23:23:53.040+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:23:53.039+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:23:53.073+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:23:53.067+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/dag_extract_despesas.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_despesas.py", line 4, in <module>
    from scripts.get_despesas_stg import extractDespesas
ModuleNotFoundError: No module named 'scripts'
[2023-11-23T23:23:53.076+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:23:53.125+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_extract_despesas.py took 0.095 seconds
[2023-11-23T23:24:23.489+0000] {processor.py:157} INFO - Started process (PID=2516) to work on /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:24:23.491+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_extract_despesas.py for tasks to queue
[2023-11-23T23:24:23.493+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:24:23.493+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:24:23.528+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:24:23.521+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/dag_extract_despesas.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_despesas.py", line 4, in <module>
    from scripts.get_despesas_stg import extractDespesas
ModuleNotFoundError: No module named 'scripts'
[2023-11-23T23:24:23.530+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:24:23.550+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_extract_despesas.py took 0.064 seconds
[2023-11-23T23:24:53.961+0000] {processor.py:157} INFO - Started process (PID=2571) to work on /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:24:53.962+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_extract_despesas.py for tasks to queue
[2023-11-23T23:24:53.965+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:24:53.965+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:24:54.000+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:24:53.993+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/dag_extract_despesas.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_despesas.py", line 4, in <module>
    from scripts.get_despesas_stg import extractDespesas
ModuleNotFoundError: No module named 'scripts'
[2023-11-23T23:24:54.002+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:24:54.046+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_extract_despesas.py took 0.089 seconds
[2023-11-23T23:25:24.125+0000] {processor.py:157} INFO - Started process (PID=2626) to work on /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:25:24.126+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_extract_despesas.py for tasks to queue
[2023-11-23T23:25:24.129+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:25:24.129+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:25:24.166+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:25:24.160+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/dag_extract_despesas.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_despesas.py", line 4, in <module>
    from scripts.get_despesas_stg import extractDespesas
ModuleNotFoundError: No module named 'scripts'
[2023-11-23T23:25:24.169+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:25:24.220+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_extract_despesas.py took 0.099 seconds
[2023-11-23T23:25:55.085+0000] {processor.py:157} INFO - Started process (PID=2681) to work on /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:25:55.087+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_extract_despesas.py for tasks to queue
[2023-11-23T23:25:55.092+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:25:55.092+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:25:55.145+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:25:55.136+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/dag_extract_despesas.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_despesas.py", line 4, in <module>
    from scripts.get_despesas_stg import extractDespesas
ModuleNotFoundError: No module named 'scripts'
[2023-11-23T23:25:55.149+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:25:55.189+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_extract_despesas.py took 0.113 seconds
[2023-11-23T23:26:25.573+0000] {processor.py:157} INFO - Started process (PID=2736) to work on /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:26:25.575+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_extract_despesas.py for tasks to queue
[2023-11-23T23:26:25.580+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:26:25.579+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:26:25.617+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:26:25.611+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/dag_extract_despesas.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_despesas.py", line 4, in <module>
    from scripts.get_despesas_stg import extractDespesas
ModuleNotFoundError: No module named 'scripts'
[2023-11-23T23:26:25.619+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:26:25.640+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_extract_despesas.py took 0.073 seconds
[2023-11-23T23:26:56.475+0000] {processor.py:157} INFO - Started process (PID=2791) to work on /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:26:56.476+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_extract_despesas.py for tasks to queue
[2023-11-23T23:26:56.480+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:26:56.479+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:26:56.514+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:26:56.508+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/dag_extract_despesas.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_despesas.py", line 4, in <module>
    from scripts.get_despesas_stg import extractDespesas
ModuleNotFoundError: No module named 'scripts'
[2023-11-23T23:26:56.517+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:26:56.540+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_extract_despesas.py took 0.069 seconds
[2023-11-23T23:27:26.717+0000] {processor.py:157} INFO - Started process (PID=2846) to work on /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:27:26.718+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_extract_despesas.py for tasks to queue
[2023-11-23T23:27:26.721+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:27:26.721+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:27:26.756+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:27:26.750+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/dag_extract_despesas.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_despesas.py", line 4, in <module>
    from scripts.get_despesas_stg import extractDespesas
ModuleNotFoundError: No module named 'scripts'
[2023-11-23T23:27:26.759+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:27:26.796+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_extract_despesas.py took 0.084 seconds
[2023-11-23T23:27:56.994+0000] {processor.py:157} INFO - Started process (PID=2901) to work on /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:27:56.996+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_extract_despesas.py for tasks to queue
[2023-11-23T23:27:56.999+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:27:56.998+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:27:57.035+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:27:57.029+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/dag_extract_despesas.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_despesas.py", line 4, in <module>
    from scripts.get_despesas_stg import extractDespesas
ModuleNotFoundError: No module named 'scripts'
[2023-11-23T23:27:57.037+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:27:57.076+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_extract_despesas.py took 0.086 seconds
[2023-11-23T23:28:27.518+0000] {processor.py:157} INFO - Started process (PID=2956) to work on /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:28:27.519+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_extract_despesas.py for tasks to queue
[2023-11-23T23:28:27.523+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:28:27.522+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:28:27.561+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:28:27.554+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/dag_extract_despesas.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_despesas.py", line 4, in <module>
    from scripts.get_despesas_stg import extractDespesas
ModuleNotFoundError: No module named 'scripts'
[2023-11-23T23:28:27.564+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:28:27.602+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_extract_despesas.py took 0.089 seconds
[2023-11-23T23:28:58.211+0000] {processor.py:157} INFO - Started process (PID=3011) to work on /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:28:58.213+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_extract_despesas.py for tasks to queue
[2023-11-23T23:28:58.217+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:28:58.217+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:28:58.255+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:28:58.248+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/dag_extract_despesas.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_despesas.py", line 4, in <module>
    from scripts.get_despesas_stg import extractDespesas
ModuleNotFoundError: No module named 'scripts'
[2023-11-23T23:28:58.257+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:28:58.276+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_extract_despesas.py took 0.068 seconds
[2023-11-23T23:29:28.522+0000] {processor.py:157} INFO - Started process (PID=3066) to work on /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:29:28.523+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_extract_despesas.py for tasks to queue
[2023-11-23T23:29:28.526+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:29:28.526+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:29:28.559+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:29:28.552+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/dag_extract_despesas.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_despesas.py", line 4, in <module>
    from scripts.get_despesas_stg import extractDespesas
ModuleNotFoundError: No module named 'scripts'
[2023-11-23T23:29:28.562+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:29:28.602+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_extract_despesas.py took 0.084 seconds
[2023-11-23T23:29:58.976+0000] {processor.py:157} INFO - Started process (PID=3121) to work on /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:29:58.978+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_extract_despesas.py for tasks to queue
[2023-11-23T23:29:58.981+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:29:58.981+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:29:59.016+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:29:59.009+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/dag_extract_despesas.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_despesas.py", line 4, in <module>
    from scripts.get_despesas_stg import extractDespesas
ModuleNotFoundError: No module named 'scripts'
[2023-11-23T23:29:59.018+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:29:59.041+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_extract_despesas.py took 0.069 seconds
[2023-11-23T23:30:29.261+0000] {processor.py:157} INFO - Started process (PID=3176) to work on /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:30:29.262+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_extract_despesas.py for tasks to queue
[2023-11-23T23:30:29.265+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:30:29.265+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:30:29.302+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:30:29.295+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/dag_extract_despesas.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_despesas.py", line 4, in <module>
    from scripts.get_despesas_stg import extractDespesas
ModuleNotFoundError: No module named 'scripts'
[2023-11-23T23:30:29.305+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:30:29.345+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_extract_despesas.py took 0.087 seconds
[2023-11-23T23:30:59.736+0000] {processor.py:157} INFO - Started process (PID=3231) to work on /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:30:59.738+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_extract_despesas.py for tasks to queue
[2023-11-23T23:30:59.742+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:30:59.742+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:30:59.780+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:30:59.774+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/dag_extract_despesas.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_despesas.py", line 4, in <module>
    from scripts.get_despesas_stg import extractDespesas
ModuleNotFoundError: No module named 'scripts'
[2023-11-23T23:30:59.783+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:30:59.807+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_extract_despesas.py took 0.075 seconds
[2023-11-23T23:31:30.036+0000] {processor.py:157} INFO - Started process (PID=3286) to work on /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:31:30.038+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_extract_despesas.py for tasks to queue
[2023-11-23T23:31:30.041+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:31:30.040+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:31:30.080+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:31:30.072+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/dag_extract_despesas.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_despesas.py", line 4, in <module>
    from scripts.get_despesas_stg import extractDespesas
ModuleNotFoundError: No module named 'scripts'
[2023-11-23T23:31:30.083+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:31:30.104+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_extract_despesas.py took 0.076 seconds
[2023-11-23T23:32:00.309+0000] {processor.py:157} INFO - Started process (PID=3341) to work on /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:32:00.311+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_extract_despesas.py for tasks to queue
[2023-11-23T23:32:00.314+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:32:00.313+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:32:00.350+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:32:00.343+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/dag_extract_despesas.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_despesas.py", line 4, in <module>
    from scripts.get_despesas_stg import extractDespesas
ModuleNotFoundError: No module named 'scripts'
[2023-11-23T23:32:00.353+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:32:00.396+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_extract_despesas.py took 0.090 seconds
[2023-11-23T23:32:30.716+0000] {processor.py:157} INFO - Started process (PID=3396) to work on /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:32:30.717+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_extract_despesas.py for tasks to queue
[2023-11-23T23:32:30.721+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:32:30.720+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:32:30.758+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:32:30.751+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/dag_extract_despesas.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_despesas.py", line 4, in <module>
    from scripts.get_despesas_stg import extractDespesas
ModuleNotFoundError: No module named 'scripts'
[2023-11-23T23:32:30.760+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:32:30.779+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_extract_despesas.py took 0.068 seconds
[2023-11-23T23:33:01.548+0000] {processor.py:157} INFO - Started process (PID=3451) to work on /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:33:01.549+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_extract_despesas.py for tasks to queue
[2023-11-23T23:33:01.552+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:33:01.552+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:33:01.589+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:33:01.582+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/dag_extract_despesas.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_despesas.py", line 4, in <module>
    from scripts.get_despesas_stg import extractDespesas
ModuleNotFoundError: No module named 'scripts'
[2023-11-23T23:33:01.592+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:33:01.626+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_extract_despesas.py took 0.082 seconds
[2023-11-23T23:33:32.102+0000] {processor.py:157} INFO - Started process (PID=3506) to work on /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:33:32.103+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_extract_despesas.py for tasks to queue
[2023-11-23T23:33:32.108+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:33:32.107+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:33:32.143+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:33:32.136+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/dag_extract_despesas.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_despesas.py", line 4, in <module>
    from scripts.get_despesas_stg import extractDespesas
ModuleNotFoundError: No module named 'scripts'
[2023-11-23T23:33:32.146+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:33:32.171+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_extract_despesas.py took 0.073 seconds
[2023-11-23T23:33:33.784+0000] {processor.py:157} INFO - Started process (PID=3512) to work on /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:33:33.785+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_extract_despesas.py for tasks to queue
[2023-11-23T23:33:33.789+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:33:33.789+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:33:33.849+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:33:33.841+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/dag_extract_despesas.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_despesas.py", line 4, in <module>
    from scripts.get_despesas_stg import extractDespesas
ModuleNotFoundError: No module named 'scripts'
[2023-11-23T23:33:33.852+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:33:33.878+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_extract_despesas.py took 0.098 seconds
[2023-11-23T23:34:04.226+0000] {processor.py:157} INFO - Started process (PID=3567) to work on /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:34:04.228+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_extract_despesas.py for tasks to queue
[2023-11-23T23:34:04.231+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:34:04.231+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:34:04.274+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:34:04.266+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/dag_extract_despesas.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_despesas.py", line 4, in <module>
    from scripts.get_despesas_stg import extractDespesas
ModuleNotFoundError: No module named 'scripts'
[2023-11-23T23:34:04.276+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:34:04.298+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_extract_despesas.py took 0.076 seconds
[2023-11-23T23:34:34.371+0000] {processor.py:157} INFO - Started process (PID=3621) to work on /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:34:34.373+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_extract_despesas.py for tasks to queue
[2023-11-23T23:34:34.376+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:34:34.376+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:34:34.412+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:34:34.405+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/dag_extract_despesas.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_despesas.py", line 4, in <module>
    from scripts.get_despesas_stg import extractDespesas
ModuleNotFoundError: No module named 'scripts'
[2023-11-23T23:34:34.414+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:34:34.435+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_extract_despesas.py took 0.069 seconds
[2023-11-23T23:35:04.694+0000] {processor.py:157} INFO - Started process (PID=3673) to work on /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:35:04.695+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_extract_despesas.py for tasks to queue
[2023-11-23T23:35:04.699+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:35:04.698+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:35:04.730+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:35:04.724+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/dag_extract_despesas.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_despesas.py", line 4, in <module>
    from scripts.get_despesas_stg import extractDespesas
ModuleNotFoundError: No module named 'scripts'
[2023-11-23T23:35:04.733+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:35:04.780+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_extract_despesas.py took 0.090 seconds
[2023-11-23T23:35:35.004+0000] {processor.py:157} INFO - Started process (PID=3729) to work on /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:35:35.005+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_extract_despesas.py for tasks to queue
[2023-11-23T23:35:35.008+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:35:35.008+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:35:35.042+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:35:35.035+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/dag_extract_despesas.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_despesas.py", line 4, in <module>
    from scripts.get_despesas_stg import extractDespesas
ModuleNotFoundError: No module named 'scripts'
[2023-11-23T23:35:35.045+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:35:35.075+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_extract_despesas.py took 0.075 seconds
[2023-11-23T23:36:05.306+0000] {processor.py:157} INFO - Started process (PID=3784) to work on /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:36:05.307+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_extract_despesas.py for tasks to queue
[2023-11-23T23:36:05.310+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:36:05.310+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:36:05.347+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:36:05.340+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/dag_extract_despesas.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_despesas.py", line 4, in <module>
    from scripts.get_despesas_stg import extractDespesas
ModuleNotFoundError: No module named 'scripts'
[2023-11-23T23:36:05.349+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:36:05.369+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_extract_despesas.py took 0.066 seconds
[2023-11-23T23:36:36.307+0000] {processor.py:157} INFO - Started process (PID=3839) to work on /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:36:36.308+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_extract_despesas.py for tasks to queue
[2023-11-23T23:36:36.312+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:36:36.311+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:36:36.349+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:36:36.344+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/dag_extract_despesas.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_despesas.py", line 4, in <module>
    from scripts.get_despesas_stg import extractDespesas
ModuleNotFoundError: No module named 'scripts'
[2023-11-23T23:36:36.352+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:36:36.396+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_extract_despesas.py took 0.094 seconds
[2023-11-23T23:37:06.639+0000] {processor.py:157} INFO - Started process (PID=3894) to work on /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:37:06.641+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_extract_despesas.py for tasks to queue
[2023-11-23T23:37:06.644+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:37:06.643+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:37:06.680+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:37:06.674+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/dag_extract_despesas.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_despesas.py", line 4, in <module>
    from scripts.get_despesas_stg import extractDespesas
ModuleNotFoundError: No module named 'scripts'
[2023-11-23T23:37:06.682+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:37:06.720+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_extract_despesas.py took 0.085 seconds
[2023-11-23T23:37:37.100+0000] {processor.py:157} INFO - Started process (PID=3949) to work on /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:37:37.101+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_extract_despesas.py for tasks to queue
[2023-11-23T23:37:37.104+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:37:37.104+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:37:37.138+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:37:37.133+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/dag_extract_despesas.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_despesas.py", line 4, in <module>
    from scripts.get_despesas_stg import extractDespesas
ModuleNotFoundError: No module named 'scripts'
[2023-11-23T23:37:37.140+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:37:37.159+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_extract_despesas.py took 0.065 seconds
[2023-11-23T23:38:07.355+0000] {processor.py:157} INFO - Started process (PID=4004) to work on /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:38:07.357+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_extract_despesas.py for tasks to queue
[2023-11-23T23:38:07.360+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:38:07.360+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:38:07.393+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:38:07.387+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/dag_extract_despesas.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_despesas.py", line 4, in <module>
    from scripts.get_despesas_stg import extractDespesas
ModuleNotFoundError: No module named 'scripts'
[2023-11-23T23:38:07.395+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:38:07.415+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_extract_despesas.py took 0.064 seconds
[2023-11-23T23:38:37.894+0000] {processor.py:157} INFO - Started process (PID=4059) to work on /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:38:37.895+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_extract_despesas.py for tasks to queue
[2023-11-23T23:38:37.899+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:38:37.899+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:38:37.935+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:38:37.929+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/dag_extract_despesas.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_despesas.py", line 4, in <module>
    from scripts.get_despesas_stg import extractDespesas
ModuleNotFoundError: No module named 'scripts'
[2023-11-23T23:38:37.938+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:38:37.957+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_extract_despesas.py took 0.068 seconds
[2023-11-23T23:39:08.459+0000] {processor.py:157} INFO - Started process (PID=4114) to work on /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:39:08.460+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_extract_despesas.py for tasks to queue
[2023-11-23T23:39:08.464+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:39:08.463+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:39:08.504+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:39:08.497+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/dag_extract_despesas.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_despesas.py", line 4, in <module>
    from scripts.get_despesas_stg import extractDespesas
ModuleNotFoundError: No module named 'scripts'
[2023-11-23T23:39:08.507+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:39:08.550+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_extract_despesas.py took 0.095 seconds
[2023-11-23T23:39:38.900+0000] {processor.py:157} INFO - Started process (PID=4169) to work on /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:39:38.902+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_extract_despesas.py for tasks to queue
[2023-11-23T23:39:38.904+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:39:38.904+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:39:38.938+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:39:38.933+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/dag_extract_despesas.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_despesas.py", line 4, in <module>
    from scripts.get_despesas_stg import extractDespesas
ModuleNotFoundError: No module named 'scripts'
[2023-11-23T23:39:38.941+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:39:38.983+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_extract_despesas.py took 0.086 seconds
[2023-11-23T23:40:09.635+0000] {processor.py:157} INFO - Started process (PID=4224) to work on /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:40:09.637+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_extract_despesas.py for tasks to queue
[2023-11-23T23:40:09.640+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:40:09.640+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:40:09.673+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:40:09.668+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/dag_extract_despesas.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_despesas.py", line 4, in <module>
    from scripts.get_despesas_stg import extractDespesas
ModuleNotFoundError: No module named 'scripts'
[2023-11-23T23:40:09.675+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:40:09.696+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_extract_despesas.py took 0.064 seconds
[2023-11-23T23:40:39.940+0000] {processor.py:157} INFO - Started process (PID=4279) to work on /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:40:39.941+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_extract_despesas.py for tasks to queue
[2023-11-23T23:40:39.944+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:40:39.944+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:40:39.978+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:40:39.971+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/dag_extract_despesas.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_despesas.py", line 4, in <module>
    from scripts.get_despesas_stg import extractDespesas
ModuleNotFoundError: No module named 'scripts'
[2023-11-23T23:40:39.982+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:40:40.028+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_extract_despesas.py took 0.093 seconds
[2023-11-23T23:41:10.302+0000] {processor.py:157} INFO - Started process (PID=4334) to work on /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:41:10.304+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_extract_despesas.py for tasks to queue
[2023-11-23T23:41:10.307+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:41:10.307+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:41:10.343+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:41:10.336+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/dag_extract_despesas.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_despesas.py", line 4, in <module>
    from scripts.get_despesas_stg import extractDespesas
ModuleNotFoundError: No module named 'scripts'
[2023-11-23T23:41:10.345+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:41:10.365+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_extract_despesas.py took 0.068 seconds
[2023-11-23T23:41:40.827+0000] {processor.py:157} INFO - Started process (PID=4389) to work on /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:41:40.829+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_extract_despesas.py for tasks to queue
[2023-11-23T23:41:40.832+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:41:40.832+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:41:40.867+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:41:40.861+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/dag_extract_despesas.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_despesas.py", line 4, in <module>
    from scripts.get_despesas_stg import extractDespesas
ModuleNotFoundError: No module named 'scripts'
[2023-11-23T23:41:40.870+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:41:40.890+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_extract_despesas.py took 0.066 seconds
[2023-11-23T23:42:11.139+0000] {processor.py:157} INFO - Started process (PID=4444) to work on /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:42:11.141+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_extract_despesas.py for tasks to queue
[2023-11-23T23:42:11.144+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:42:11.143+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:42:11.181+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:42:11.175+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/dag_extract_despesas.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_despesas.py", line 4, in <module>
    from scripts.get_despesas_stg import extractDespesas
ModuleNotFoundError: No module named 'scripts'
[2023-11-23T23:42:11.184+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:42:11.225+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_extract_despesas.py took 0.089 seconds
[2023-11-23T23:42:41.501+0000] {processor.py:157} INFO - Started process (PID=4499) to work on /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:42:41.503+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_extract_despesas.py for tasks to queue
[2023-11-23T23:42:41.505+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:42:41.505+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:42:41.541+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:42:41.535+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/dag_extract_despesas.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_despesas.py", line 4, in <module>
    from scripts.get_despesas_stg import extractDespesas
ModuleNotFoundError: No module named 'scripts'
[2023-11-23T23:42:41.544+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:42:41.570+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_extract_despesas.py took 0.072 seconds
[2023-11-23T23:43:12.149+0000] {processor.py:157} INFO - Started process (PID=4554) to work on /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:43:12.151+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_extract_despesas.py for tasks to queue
[2023-11-23T23:43:12.153+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:43:12.153+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:43:12.188+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:43:12.182+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/dag_extract_despesas.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_despesas.py", line 4, in <module>
    from scripts.get_despesas_stg import extractDespesas
ModuleNotFoundError: No module named 'scripts'
[2023-11-23T23:43:12.191+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:43:12.229+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_extract_despesas.py took 0.083 seconds
[2023-11-23T23:43:42.723+0000] {processor.py:157} INFO - Started process (PID=4609) to work on /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:43:42.724+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_extract_despesas.py for tasks to queue
[2023-11-23T23:43:42.727+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:43:42.726+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:43:42.758+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:43:42.751+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/dag_extract_despesas.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_despesas.py", line 4, in <module>
    from scripts.get_despesas_stg import extractDespesas
ModuleNotFoundError: No module named 'scripts'
[2023-11-23T23:43:42.761+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:43:42.783+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_extract_despesas.py took 0.064 seconds
[2023-11-23T23:44:13.073+0000] {processor.py:157} INFO - Started process (PID=4664) to work on /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:44:13.075+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_extract_despesas.py for tasks to queue
[2023-11-23T23:44:13.078+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:44:13.077+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:44:13.116+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:44:13.108+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/dag_extract_despesas.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_despesas.py", line 4, in <module>
    from scripts.get_despesas_stg import extractDespesas
ModuleNotFoundError: No module named 'scripts'
[2023-11-23T23:44:13.119+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:44:13.165+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_extract_despesas.py took 0.096 seconds
[2023-11-23T23:44:43.530+0000] {processor.py:157} INFO - Started process (PID=4726) to work on /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:44:43.532+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_extract_despesas.py for tasks to queue
[2023-11-23T23:44:43.534+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:44:43.534+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:44:43.570+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:44:43.564+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/dag_extract_despesas.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_despesas.py", line 4, in <module>
    from scripts.get_despesas_stg import extractDespesas
ModuleNotFoundError: No module named 'scripts'
[2023-11-23T23:44:43.572+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:44:43.595+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_extract_despesas.py took 0.070 seconds
[2023-11-23T23:45:13.723+0000] {processor.py:157} INFO - Started process (PID=4781) to work on /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:45:13.725+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_extract_despesas.py for tasks to queue
[2023-11-23T23:45:13.728+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:45:13.728+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:45:13.767+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:45:13.760+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/dag_extract_despesas.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_despesas.py", line 4, in <module>
    from scripts.get_despesas_stg import extractDespesas
ModuleNotFoundError: No module named 'scripts'
[2023-11-23T23:45:13.769+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:45:13.813+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_extract_despesas.py took 0.093 seconds
[2023-11-23T23:45:44.564+0000] {processor.py:157} INFO - Started process (PID=4836) to work on /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:45:44.565+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_extract_despesas.py for tasks to queue
[2023-11-23T23:45:44.569+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:45:44.569+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:45:44.605+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:45:44.599+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/dag_extract_despesas.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_despesas.py", line 4, in <module>
    from scripts.get_despesas_stg import extractDespesas
ModuleNotFoundError: No module named 'scripts'
[2023-11-23T23:45:44.608+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:45:44.659+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_extract_despesas.py took 0.099 seconds
[2023-11-23T23:46:14.865+0000] {processor.py:157} INFO - Started process (PID=4891) to work on /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:46:14.866+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_extract_despesas.py for tasks to queue
[2023-11-23T23:46:14.872+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:46:14.871+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:46:14.912+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:46:14.905+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/dag_extract_despesas.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_despesas.py", line 4, in <module>
    from scripts.get_despesas_stg import extractDespesas
ModuleNotFoundError: No module named 'scripts'
[2023-11-23T23:46:14.915+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:46:14.934+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_extract_despesas.py took 0.073 seconds
[2023-11-23T23:46:45.535+0000] {processor.py:157} INFO - Started process (PID=4946) to work on /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:46:45.536+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_extract_despesas.py for tasks to queue
[2023-11-23T23:46:45.540+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:46:45.539+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:46:45.576+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:46:45.569+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/dag_extract_despesas.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_despesas.py", line 4, in <module>
    from scripts.get_despesas_stg import extractDespesas
ModuleNotFoundError: No module named 'scripts'
[2023-11-23T23:46:45.578+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:46:45.627+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_extract_despesas.py took 0.096 seconds
[2023-11-23T23:47:15.979+0000] {processor.py:157} INFO - Started process (PID=5001) to work on /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:47:15.981+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_extract_despesas.py for tasks to queue
[2023-11-23T23:47:15.985+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:47:15.984+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:47:16.020+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:47:16.014+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/dag_extract_despesas.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_despesas.py", line 4, in <module>
    from scripts.get_despesas_stg import extractDespesas
ModuleNotFoundError: No module named 'scripts'
[2023-11-23T23:47:16.022+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:47:16.071+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_extract_despesas.py took 0.097 seconds
[2023-11-23T23:47:46.392+0000] {processor.py:157} INFO - Started process (PID=5056) to work on /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:47:46.394+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_extract_despesas.py for tasks to queue
[2023-11-23T23:47:46.398+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:47:46.397+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:47:46.437+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:47:46.429+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/dag_extract_despesas.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_despesas.py", line 4, in <module>
    from scripts.get_despesas_stg import extractDespesas
ModuleNotFoundError: No module named 'scripts'
[2023-11-23T23:47:46.440+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:47:46.491+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_extract_despesas.py took 0.104 seconds
[2023-11-23T23:48:17.187+0000] {processor.py:157} INFO - Started process (PID=5111) to work on /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:48:17.189+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_extract_despesas.py for tasks to queue
[2023-11-23T23:48:17.192+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:48:17.192+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:48:17.233+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:48:17.226+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/dag_extract_despesas.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_despesas.py", line 4, in <module>
    from scripts.get_despesas_stg import extractDespesas
ModuleNotFoundError: No module named 'scripts'
[2023-11-23T23:48:17.236+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:48:17.283+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_extract_despesas.py took 0.100 seconds
[2023-11-23T23:48:47.675+0000] {processor.py:157} INFO - Started process (PID=5166) to work on /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:48:47.677+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_extract_despesas.py for tasks to queue
[2023-11-23T23:48:47.680+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:48:47.680+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:48:47.713+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:48:47.706+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/dag_extract_despesas.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_despesas.py", line 4, in <module>
    from scripts.get_despesas_stg import extractDespesas
ModuleNotFoundError: No module named 'scripts'
[2023-11-23T23:48:47.715+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:48:47.764+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_extract_despesas.py took 0.092 seconds
[2023-11-23T23:49:18.138+0000] {processor.py:157} INFO - Started process (PID=5221) to work on /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:49:18.140+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_extract_despesas.py for tasks to queue
[2023-11-23T23:49:18.143+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:49:18.143+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:49:18.179+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:49:18.173+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/dag_extract_despesas.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_despesas.py", line 4, in <module>
    from scripts.get_despesas_stg import extractDespesas
ModuleNotFoundError: No module named 'scripts'
[2023-11-23T23:49:18.182+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:49:18.219+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_extract_despesas.py took 0.085 seconds
[2023-11-23T23:49:48.510+0000] {processor.py:157} INFO - Started process (PID=5276) to work on /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:49:48.511+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_extract_despesas.py for tasks to queue
[2023-11-23T23:49:48.514+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:49:48.514+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:49:48.554+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:49:48.548+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/dag_extract_despesas.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_despesas.py", line 4, in <module>
    from scripts.get_despesas_stg import extractDespesas
ModuleNotFoundError: No module named 'scripts'
[2023-11-23T23:49:48.557+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:49:48.595+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_extract_despesas.py took 0.090 seconds
[2023-11-23T23:50:18.775+0000] {processor.py:157} INFO - Started process (PID=5331) to work on /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:50:18.777+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_extract_despesas.py for tasks to queue
[2023-11-23T23:50:18.780+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:50:18.780+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:50:18.810+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:50:18.805+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/dag_extract_despesas.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_despesas.py", line 4, in <module>
    from scripts.get_despesas_stg import extractDespesas
ModuleNotFoundError: No module named 'scripts'
[2023-11-23T23:50:18.812+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:50:18.832+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_extract_despesas.py took 0.061 seconds
[2023-11-23T23:50:49.511+0000] {processor.py:157} INFO - Started process (PID=5386) to work on /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:50:49.513+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_extract_despesas.py for tasks to queue
[2023-11-23T23:50:49.516+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:50:49.516+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:50:49.556+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:50:49.549+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/dag_extract_despesas.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_despesas.py", line 4, in <module>
    from scripts.get_despesas_stg import extractDespesas
ModuleNotFoundError: No module named 'scripts'
[2023-11-23T23:50:49.561+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:50:49.605+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_extract_despesas.py took 0.097 seconds
[2023-11-23T23:51:19.949+0000] {processor.py:157} INFO - Started process (PID=5441) to work on /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:51:19.951+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_extract_despesas.py for tasks to queue
[2023-11-23T23:51:19.954+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:51:19.954+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:51:19.988+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:51:19.981+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/dag_extract_despesas.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_despesas.py", line 4, in <module>
    from scripts.get_despesas_stg import extractDespesas
ModuleNotFoundError: No module named 'scripts'
[2023-11-23T23:51:19.990+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:51:20.011+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_extract_despesas.py took 0.067 seconds
[2023-11-23T23:51:50.430+0000] {processor.py:157} INFO - Started process (PID=5496) to work on /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:51:50.432+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_extract_despesas.py for tasks to queue
[2023-11-23T23:51:50.435+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:51:50.434+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:51:50.471+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:51:50.465+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/dag_extract_despesas.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_despesas.py", line 4, in <module>
    from scripts.get_despesas_stg import extractDespesas
ModuleNotFoundError: No module named 'scripts'
[2023-11-23T23:51:50.473+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:51:50.497+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_extract_despesas.py took 0.071 seconds
[2023-11-23T23:52:20.812+0000] {processor.py:157} INFO - Started process (PID=5551) to work on /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:52:20.836+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_extract_despesas.py for tasks to queue
[2023-11-23T23:52:20.888+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:52:20.886+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:52:21.028+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:52:21.003+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/dag_extract_despesas.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_despesas.py", line 4, in <module>
    from scripts.get_despesas_stg import extractDespesas
ModuleNotFoundError: No module named 'scripts'
[2023-11-23T23:52:21.039+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:52:22.303+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_extract_despesas.py took 1.573 seconds
[2023-11-23T23:52:52.996+0000] {processor.py:157} INFO - Started process (PID=5605) to work on /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:52:52.998+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_extract_despesas.py for tasks to queue
[2023-11-23T23:52:53.004+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:52:53.004+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:52:53.051+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:52:53.041+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/dag_extract_despesas.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_despesas.py", line 4, in <module>
    from scripts.get_despesas_stg import extractDespesas
ModuleNotFoundError: No module named 'scripts'
[2023-11-23T23:52:53.054+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:52:53.090+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_extract_despesas.py took 0.107 seconds
[2023-11-23T23:53:23.275+0000] {processor.py:157} INFO - Started process (PID=5660) to work on /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:53:23.277+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_extract_despesas.py for tasks to queue
[2023-11-23T23:53:23.281+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:53:23.280+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:53:23.319+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:53:23.313+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/dag_extract_despesas.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_despesas.py", line 4, in <module>
    from scripts.get_despesas_stg import extractDespesas
ModuleNotFoundError: No module named 'scripts'
[2023-11-23T23:53:23.321+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:53:23.350+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_extract_despesas.py took 0.079 seconds
[2023-11-23T23:53:53.774+0000] {processor.py:157} INFO - Started process (PID=5715) to work on /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:53:53.776+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_extract_despesas.py for tasks to queue
[2023-11-23T23:53:53.780+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:53:53.780+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:53:53.829+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:53:53.818+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/dag_extract_despesas.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_despesas.py", line 4, in <module>
    from scripts.get_despesas_stg import extractDespesas
ModuleNotFoundError: No module named 'scripts'
[2023-11-23T23:53:53.832+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:53:53.861+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_extract_despesas.py took 0.093 seconds
[2023-11-23T23:54:24.117+0000] {processor.py:157} INFO - Started process (PID=5770) to work on /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:54:24.121+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_extract_despesas.py for tasks to queue
[2023-11-23T23:54:24.133+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:54:24.132+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:54:24.262+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:54:24.233+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/dag_extract_despesas.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_despesas.py", line 4, in <module>
    from scripts.get_despesas_stg import extractDespesas
ModuleNotFoundError: No module named 'scripts'
[2023-11-23T23:54:24.271+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:54:24.381+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_extract_despesas.py took 0.282 seconds
[2023-11-23T23:54:55.359+0000] {processor.py:157} INFO - Started process (PID=5825) to work on /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:54:55.361+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_extract_despesas.py for tasks to queue
[2023-11-23T23:54:55.365+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:54:55.364+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:54:55.395+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:54:55.389+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/dag_extract_despesas.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_despesas.py", line 4, in <module>
    from scripts.get_despesas_stg import extractDespesas
ModuleNotFoundError: No module named 'scripts'
[2023-11-23T23:54:55.397+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:54:55.436+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_extract_despesas.py took 0.081 seconds
[2023-11-23T23:55:25.918+0000] {processor.py:157} INFO - Started process (PID=5880) to work on /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:55:25.922+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_extract_despesas.py for tasks to queue
[2023-11-23T23:55:25.938+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:55:25.937+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:55:26.041+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:55:26.024+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/dag_extract_despesas.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_despesas.py", line 4, in <module>
    from scripts.get_despesas_stg import extractDespesas
ModuleNotFoundError: No module named 'scripts'
[2023-11-23T23:55:26.048+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:55:26.139+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_extract_despesas.py took 0.233 seconds
[2023-11-23T23:55:56.662+0000] {processor.py:157} INFO - Started process (PID=5935) to work on /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:55:56.666+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_extract_despesas.py for tasks to queue
[2023-11-23T23:55:56.697+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:55:56.696+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:55:56.962+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:55:56.944+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/dag_extract_despesas.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_despesas.py", line 4, in <module>
    from scripts.get_despesas_stg import extractDespesas
ModuleNotFoundError: No module named 'scripts'
[2023-11-23T23:55:56.967+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:55:57.270+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_extract_despesas.py took 0.695 seconds
[2023-11-23T23:56:28.121+0000] {processor.py:157} INFO - Started process (PID=5990) to work on /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:56:28.125+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_extract_despesas.py for tasks to queue
[2023-11-23T23:56:28.133+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:56:28.132+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:56:28.183+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:56:28.174+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/dag_extract_despesas.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_despesas.py", line 4, in <module>
    from scripts.get_despesas_stg import extractDespesas
ModuleNotFoundError: No module named 'scripts'
[2023-11-23T23:56:28.185+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:56:28.253+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_extract_despesas.py took 0.137 seconds
[2023-11-23T23:56:58.781+0000] {processor.py:157} INFO - Started process (PID=6045) to work on /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:56:58.784+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_extract_despesas.py for tasks to queue
[2023-11-23T23:56:58.789+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:56:58.789+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:56:58.837+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:56:58.828+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/dag_extract_despesas.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_despesas.py", line 4, in <module>
    from scripts.get_despesas_stg import extractDespesas
ModuleNotFoundError: No module named 'scripts'
[2023-11-23T23:56:58.840+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:56:58.898+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_extract_despesas.py took 0.124 seconds
[2023-11-23T23:57:29.589+0000] {processor.py:157} INFO - Started process (PID=6100) to work on /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:57:29.590+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_extract_despesas.py for tasks to queue
[2023-11-23T23:57:29.593+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:57:29.593+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:57:29.632+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:57:29.625+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/dag_extract_despesas.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_despesas.py", line 4, in <module>
    from scripts.get_despesas_stg import extractDespesas
ModuleNotFoundError: No module named 'scripts'
[2023-11-23T23:57:29.634+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:57:29.654+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_extract_despesas.py took 0.069 seconds
[2023-11-23T23:58:00.040+0000] {processor.py:157} INFO - Started process (PID=6155) to work on /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:58:00.042+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_extract_despesas.py for tasks to queue
[2023-11-23T23:58:00.045+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:58:00.045+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:58:00.086+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:58:00.077+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/dag_extract_despesas.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_despesas.py", line 4, in <module>
    from scripts.get_despesas_stg import extractDespesas
ModuleNotFoundError: No module named 'scripts'
[2023-11-23T23:58:00.088+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:58:00.111+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_extract_despesas.py took 0.074 seconds
[2023-11-23T23:58:30.176+0000] {processor.py:157} INFO - Started process (PID=6210) to work on /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:58:30.177+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_extract_despesas.py for tasks to queue
[2023-11-23T23:58:30.180+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:58:30.180+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:58:30.208+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:58:30.203+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/dag_extract_despesas.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_despesas.py", line 4, in <module>
    from scripts.get_despesas_stg import extractDespesas
ModuleNotFoundError: No module named 'scripts'
[2023-11-23T23:58:30.210+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:58:30.293+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_extract_despesas.py took 0.121 seconds
[2023-11-23T23:59:00.361+0000] {processor.py:157} INFO - Started process (PID=6265) to work on /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:59:00.362+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_extract_despesas.py for tasks to queue
[2023-11-23T23:59:00.365+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:59:00.365+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:59:00.401+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:59:00.394+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/dag_extract_despesas.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_despesas.py", line 4, in <module>
    from scripts.get_despesas_stg import extractDespesas
ModuleNotFoundError: No module named 'scripts'
[2023-11-23T23:59:00.403+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:59:00.428+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_extract_despesas.py took 0.071 seconds
[2023-11-23T23:59:30.713+0000] {processor.py:157} INFO - Started process (PID=6320) to work on /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:59:30.714+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_extract_despesas.py for tasks to queue
[2023-11-23T23:59:30.717+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:59:30.717+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:59:30.751+0000] {logging_mixin.py:154} INFO - [2023-11-23T23:59:30.745+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/dag_extract_despesas.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_despesas.py", line 4, in <module>
    from scripts.get_despesas_stg import extractDespesas
ModuleNotFoundError: No module named 'scripts'
[2023-11-23T23:59:30.753+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_despesas.py
[2023-11-23T23:59:30.799+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_extract_despesas.py took 0.091 seconds
